export const c1Styles = {
  common: {
    configurationContents: 'tw-mx-60-px tw-shadow-shadow-level-1',
    configurationContentsDashboard: '',
    mainComponentPadding: 'tw-px-60-px',
    mainComponentShadow: 'tw-shadow-shadow-level-1',
    inputLabelTextStyle: 'tw-pt-4-px',
    configurationBrandingClass: 'co',
    paginatorContainer: 'tw-rounded-b-8-px',
    dialogHeaderText: 'tw-text-text-primary tw-text-20-px tw-font-600 tw-line-height-20',
    dialogSubDescriptionContainer:
      'tw-flex tw-justify-start tw-px-24-px tw-pt-24-px tw-pb-16-px tw-border-separator tw-border-t',
    dialogDescriptionText: 'tw-hidden',
    dialogSubDescriptionText: 'tw-text-text-primary tw-text-14-px tw-font-400',
  },
  mapping: {
    mappingHeaderBoxShadow: 'tw-shadow-shadow-level-1',
  },
  configuration: {
    importSvgPadding: 'tw-pt-10-px',
    importFieldDependentField: 'tw-pr-24-px tw-pl-[58px]',
    importFieldDependentFieldSvg: 'tw-pt-42-px',
    importFieldDropDownText: '!tw-font-600 tw-text-12-px',
    stepHeaderH3Text: 'tw-text-16-px',
    stepDescriptionText: 'tw-text-12-px text-secondary-neutral',
    searchIconFocus: 'tw-text-search-focused-filled-border',
    settingsContainer: 'tw-rounded-8-px',
    settingsHeader: 'tw-p-24-px',
    infoLabelBackground: 'tw-py-8-px tw-px-12-px tw-rounded-4-px tw-bg-bg-blue',
    infoLabelIcon: 'tw-text-icon-blue',
    autoSyncPaymentPreviewInfoLabelIcon: 'tw-text-muted',
    infoLabelText: 'tw-text-12-px tw-font-400 tw-self-center tw-text-text-primary',
    configurationExportCard: 'tw-border tw-border-solid tw-border-tertiary-lighter tw-rounded-8-px',
    configurationExportCardSecondary: 'tw-bg-white tw-border tw-border-solid tw-border-separator tw-rounded-8-px',
    configurationExportCardTertiary: 'tw-bg-white tw-border tw-border-solid tw-border-border-tertiary tw-rounded-8-px',
    configurationImportCard: 'tw-rounded-8-px tw-border-tertiary-lighter tw-border',
    configurationAdvancedSettingAutomationCardHeader: '',
    configurationAdvancedSettingAutomationCardBody:
      'tw-border-separator tw-border-x tw-border-b tw-mb-16-px tw-rounded-b-8-px',
    configurationAdvancedSettingCustomizationCardHeader: 'tw-mt-16-px tw-rounded-t-8-px',
    configurationAdvancedSettingCustomizationCardBody: 'tw-border-separator tw-border-x tw-border-b tw-rounded-b-8-px',
    configurationAdvancedSettingNetsuiteCardBody:
      'tw-border-separator tw-border-x tw-border-b tw-rounded-b-8-px tw-bg-white tw-mb-16-px',
    configurationAdvancedSettingDefaultFieldCard:
      'tw-pb-24-px tw-bg-white tw-border-separator tw-border-x tw-border-b tw-rounded-b-8-px',
    configurationAdvancedSettingSingleCard: 'tw-rounded-8-px tw-border-separator tw-border',
    configurationFieldHeaderText: 'tw-text-text-primary !tw-font-600',
  },
  dashboard: {
    dashboardErrorResolveBtnText: 'p-button primary-outline',
    dashboardExportBtn: 'tw-rounded-4-px',
    dashboardMainMenu: 'tw-items-center',
    exportSummaryHeaderText: 'tw-font-600 tw-text-14-px',
    exportSummaryDescriptionText: 'tw-font-400 tw-text-text-primary',
    exportSummaryViewText: 'link tw-text-text-primary tw-font-400',
    exportSummaryContentCard: 'tw-px-0 tw-py-0',
    exportSummaryCenterContent: 'tw-mt-12-px tw-mb-16-px tw-border-b tw-border-tertiary-lighter',
    exportSummaryIcon: '',
    exportSummaryCountText: 'tw--ml-10-px',
    exportSectionHeaderText: 'tw-text-14-px tw-font-600 tw-text-text-primary',
    exportSectionDescriptionText: 'tw-mt-4-px tw-text-12-px tw-font-400 tw-text-sub-text-color',
    exportSectionDescriptionSubText: '',
    exportErrorSectionHeaderText: '!tw-font-600 !tw-text-14-px',
    exportErrorSubTextContainer: 'tw-rounded-4-px tw-py-8-px tw-px-12-px tw-bg-[#EBF8FF]',
    exportErrorSubTextHeader: 'tw-text-12-px !tw-font-600',
    exportErrorSubTextDescription: '!tw-text-text-primary tw-text-12-px !tw-font-400 tw-pt-4-px',
    exportErrorTextHeader: 'tw-text-12-px !tw-font-600 tw-text-text-primary',
    exportErrorTextDescription: '!tw-text-text-primary tw-text-12-px tw-pt-4-px !tw-font-400 !tw-leading-4',
    exportErrorCard:
      'tw-flex tw-justify-between tw-items-start tw-gap-4 tw-border-solid tw-border-1-px tw-border-border-tertiary tw-rounded-4-px tw-py-8-px tw-px-12-px',
    exportErrorCardButton: '',
    exportErrorAccountingDescription: '!tw-text-text-primary tw-pt-4-px',
    exportErrorDescriptionText: 'tw-text-text-primary',
    zeroStateHeaderText: 'tw-font-600',
    zeroStateDescriptionText: 'tw-pt-20-px tw-max-w-xs',
    subMenuContainer: 'tw-px-24-px tw-rounded-t-8-px',
    mapping: {
      background: 'tw-bg-white tw-rounded-8-px tw-shadow-md',
      mainComponentCard: 'tw-rounded-8-px tw-bg-white',
      countCardsContainer: 'tw-mx-24-px tw-mt-24-px tw--mb-20-px',
      countText: 'tw-text-20-px tw-font-600 tw-pt-2-px',
      headerCard: 'tw-bg-white tw-shadow-mapping-card',
    },
  },
  checkbok: {
    theme: 'co-checkbox',
  },
  qbd_direct: {
    onboarding: {
      preRequisiteContainer: 'tw-rounded-border-radius-full',
      preRequisiteCard:
        'tw-rounded-8-px tw-border-1-px tw-border-bg-brand tw-py-24-px tw-pl-24-px tw-pr-8-px tw-my-24-px',
      preRequisiteHeaderText: 'tw-text-14-px tw-font-600',
      preRequisiteDescriptionText: 'tw-text-12-px tw-font-400',
      preRequisiteHeaderFont: 'tw-text-text-primary',
      preRequisiteDescriptionFont: 'tw-text-text-primary',
      optionStepStateBackground: 'tw-bg-bg-primary',
      tutorialvideoClass: 'tw-rounded-16-px tw-w-[500px] tw-h-[250px]',
      logoSectionStyle: '',
      headerTopText: 'tw-text-14-px tw-font-600',
      headerDescriptionText: 'tw-text-12-px',
      bodyTopText: 'tw-text-18-px tw-font-600',
      headerStyle: 'tw-bg-bg-white tw-mx-[40px] tw-my-[24px] tw-rounded-xl tw-shadow-onboarding-card',
      headerCenterContent: 'tw-justify-center',
      bodyStyle: 'tw-py-24-px tw-bg-bg-white tw-mx-[40px] tw-my-[24px] tw-rounded-xl tw-shadow-onboarding-card',
      flowChart: 'tw-mt-50-px',
      stepStateHeaderText: 'tw-font-600 tw-text-text-primary',
      downloadFileButton: 'tw-flex tw-w-auto tw-inline-flex tw-items-center tw-justify-center',
      downloadFileHeader: 'tw-flex tw-flex-col-reverse tw-gap-4',
      downloadHeaderText: 'tw-text-14-px tw-font-600 tw-text-text-primary',
      downloadDescriptionText: 'tw-text-14-px tw-text-text-primary',
      downloadFileSuccessDescription: 'tw-text-text-primary tw-text-14-px',
      stepStateCard: 'tw-border-tertiary-lighter',
      connectorDescription: 'tw-hidden',
      connectorHeader: 'tw-text-text-primary tw-font-400',
      connectorText: 'tw-pt-24-px',
      connectorHighlightText: 'tw-font-600',
      connectorPassword: 'tw-pr-4-px',
      connectorPasswordText: 'tw-text-14-px tw-text-text-primary tw-font-600',
      connectorPasswordIconColor: 'tw-text-icon-blue',
      connectorSideVideoCard: 'tw-border tw-border-border-grey tw-rounded-8-px',
      connectorSideVideoFrame: 'tw-rounded-tl-8-px tw-rounded-tr-8-px',
      connectorTutorialDescription: '',
      connectorSuccessHeader: 'tw-text-text-primary tw-text-14-px tw-font-600',
      connectorSuccessDescription: 'tw-hidden',
      downloadFileVideoCard: 'tw-border tw-border-border-grey tw-rounded-8-px',
      downloadFileVideoFrame: 'tw-rounded-tl-8-px tw-rounded-tr-8-px',
      dataSyncText: 'tw-text-text-primary',
      dataSyncContent: 'tw-flex tw-flex-col-reverse tw-mt-24-px',
      dataSyncIcon: 'tw-text-icon-grey',
      configurationHeaderText: 'tw-text-text-primary !tw-font-600',
      configurationDescriptionText: 'tw-text-text-primary',
      configurationToggleHeaderText: 'tw-text-text-primary tw-text-14-px !tw-font-600',
      configurationToggleDescriptionText: '!tw-text-sub-text-color tw-text-12-px !tw-font-400',
      configurationSelectFieldHeaderText: 'tw-text-text-primary tw-text-14-px !tw-font-600',
      configurationSelectFieldDescriptionText: '!tw-text-sub-text-color tw-text-12-px !tw-font-400',
      configurationStepSubHeaderCard: 'tw-rounded-t-8-px tw-bg-bg-white',
      configurationStepSubHeaderText: 'tw-font-600',
      configurationStepSubHeaderDescription: 'tw-text-text-primary',
      configurationDoneHeader: '!tw-font-600',
      configurationDoneDescription: 'tw-pt-20-px',
    },
  },
  buttons: {
    primary: {
      class: 'p-button p-button-raised tw-rounded-md',
      active: 'tw-bg-primary tw-font-600',
      disabled: 'p-disabled tw-text-text-placeholder tw-cursor-not-allowed',
      progress: 'p-disabled tw-text-text-placeholder tw-cursor-not-allowed',
      loader: 'tw-border-t-border-tertiary',
      iconColorActive: 'tw-text-white',
      iconColorHover: '',
      iconColorDisabled: 'tw-text-text-placeholder',
    },
    secondary: {
      class:
        'tw-h-38-px tw-rounded-4-px tw-border tw-text-text-brand-primary tw-font-nav-link-font-weight tw-border-solid tw-border-btn-outline-primary-border-color',
      active:
        'hover:tw-text-btn-outline-primary-hover-text-color hover:tw-bg-btn-outline-primary-hover-bg tw-text-size-14 tw-bg-btn-outline-primary-bg tw-border-grey-300 tw-font-500 tw-cursor-pointer',
      disabled: 'tw-text-text-placeholder tw-cursor-not-allowed',
      progress: '',
      loader: '',
      iconColorActive: 'tw-text-text-secondary',
      iconColorHover: '',
      iconColorDisabled: 'tw-text-text-placeholder',
    },
    tertiary: {
      class:
        'tw-h-38-px tw-rounded-4-px tw-border tw-text-text-brand-primary tw-font-nav-link-font-weight tw-border-solid tw-border-btn-outline-primary-border-color',
      active:
        'hover:tw-text-btn-outline-primary-hover-text-color hover:tw-bg-btn-outline-primary-hover-bg tw-text-size-14 tw-bg-btn-outline-primary-bg tw-border-grey-300 tw-font-500 tw-cursor-pointer',
      disabled: 'tw-text-text-placeholder tw-cursor-not-allowed',
      progress: '',
      loader: '',
      iconColorActive: 'tw-text-text-secondary',
      iconColorHover: '',
      iconColorDisabled: 'tw-text-text-placeholder',
    },
    dialog: {
      cancel: 'outline-sm',
    },
  },
  checkbox: {
    text: 'tw-text-text-primary tw-text-12-px tw-font-600',
  },
  toast: {
    class: 'tw-flex tw-justify-between tw-items-center tw-h-44-px tw-text-14-px tw-p-12-px',
    leftIcon: {
      class: 'tw-inline-flex tw-items-center',
      iconSize: '20px',
      background: {
        success: '',
        error: '',
        info: '',
      },
    },
    message: 'tw-text-toast-text-color tw-pl-8-px',
    close: {
      class: 'tw-inline-flex tw-items-center tw-cursor-pointer',
      iconSize: '20px',
      iconStyleClasses: 'tw-text-toast-text-color',
    },
    backgroundClass: {
      success: 'tw-bg-toast-success-bg',
      error: 'tw-bg-toast-error-bg',
      info: 'tw-bg-bg-info',
    },
  },
};
