name: Build and Deploy Storybook to Github Page

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

permissions:
  contents: write

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: Install dependency
        run: npm i
      - name: Build storybook
        run: npm run build-storybook
      - name: Deploy to github page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
